export const GET_CONVERSATIONS_SUCCESS = 'GET_CONVERSATIONS_SUCCESS';
export const GET_CONVERSATIONS_FAILUR = 'GET_CONVERSATIONS_FAILUR';
export const GET_CONVERSATION_FETCH = 'GET_CONVERSATION_FETCH';