export const GET_CONVERSATIONS_SUCCESS = 'GET_CONVERSATIONS_SUCCESS';
export const GET_CONVERSATIONS_FAILUR = 'GET_CONVERSATIONS_FAILUR';
export const GET_CONVERSATION_FETCH = 'GET_CONVERSATION_FETCH';
export const SET_CURRENT_CHAT = 'SET_CURRENT_CHAT';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAILUR = 'GET_MESSAGES_FAILUR';